# Copyright (c) 2022-2023 Jonah Aragon <jonah@triplebit.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

name: 🏗️ Build Websites

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        language: [es, fr, he, it, nl, ru, zh-Hant]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout website
        uses: actions/checkout@v3
        with:
          repository: 'privacyguides/privacyguides.org'
          fetch-depth: '0'
          ssh-key: ${{ secrets.ACTIONS_SSH_KEY }}
          submodules: 'true'
      
      - name: Checkout translations
        uses: actions/checkout@v3
        with:
          path: 'i18n-download'
      
      - name: Move translations to site
        run: |
          cp -rl i18n-download/i18n .
          cp -rl i18n-download/includes .
          cp -rl i18n-download/theme .

      - name: Python setup
        uses: actions/setup-python@v4
        id: py38
        with:
          python-version: '3.8'
          cache: 'pipenv'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install
          sudo apt install pngquant
          echo '${{ steps.py38.outputs.cache-hit }}'

      - name: Build website
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARDS: true
        run: |
          pipenv run mkdocs build --config-file config/mkdocs.${{ matrix.language }}.yml
          pipenv run mkdocs --version

      - name: Package website
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.language }}
          path: site/${{ matrix.language }}
